# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e5ee6ff1272431c9975d78131277325d30da60232fd07c5d01eb74aea95320cfc09df5d7298fc061971b0b300f5e4c6c23c59fa51d8b2bd0944c7cd4681f9a6

test:
  secret_key_base: 95f09c9f42965643e0ab0840bb13aaf3800b35e74ead3238ab99921b539cb82686a4508343f9988b106e93b98ae22e4438fa1bbd03d847fa84c8a0583c61e7a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
